Description: CFN template to launch  a Debian EC2 instance for auto-scalling purpose

Resources:
  AutoScalingLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:  ASLaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.micro
        KeyName: assignment-key-pair

  DebianInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09a41e26df464c548
      LaunchTemplate:
        LaunchTemplateId: !Ref AutoScalingLaunchTemplate
        Version: !GetAtt AutoScalingLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: DebianInsByLT


  ASGLlaunchConfig:
      Type: AWS::AutoScaling::LaunchConfiguration
      Properties:
        InstanceId: !Ref DebianInstance
        ImageId: ami-09a41e26df464c548
        InstanceType: t2.micro

  ASG1:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: lab-6-1-4
      LaunchConfigurationName: !Ref ASGLlaunchConfig
      AvailabilityZones:
          - us-east-1b
      MaxSize: 1
      MinSize: 1
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true


#Outputs:
#  InstanceId:
#    Description: Instance ID
#    Export:
#      Name: Output-Debian-Instance-Id
#    Value: !Ref DebianInstance
