Description: CFN template to launch  a Debian EC2 instance for auto-scalling purpose

Resources:
  AutoScalingLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: ASLaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-09a41e26df464c548
        KeyName: assignment-key-pair

  ASG2:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
#      AutoScalingGroupName: lab-6-1-4-4
      LaunchTemplate:
        LaunchTemplateId:
          LaunchTemplateId: !Ref AutoScalingLaunchTemplate
          Version: GetAtt AutoScalingLaunchTemplate.LatestVersionNumber
#      LaunchConfigurationName: !Ref ASGLlaunchConfig
      AvailabilityZones:
        - us-east-1b
      MaxSize: 1
      MinSize: 1
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: true

